#spring.datasource.url=jdbc:mysql://localhost/bootdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.platform=mysql

spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(CONNECT_TIMEOUT=30)(RETRY_COUNT=20)(RETRY_DELAY=3)(ADDRESS_LIST=(LOAD_BALANCE=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=51521)))(CONNECT_DATA=(SERVICE_NAME=DEVPDB)))
spring.datasource.username=MRD_SCHEMA_OWNER
spring.datasource.password=MrdReport678
spring.datasource.driver-class=oracle.jdbc.driver.OracleDriver

spring.datasource.initialization-mode=always
logging.level.org.springframework=DEBUG
