server.port=8088

spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(CONNECT_TIMEOUT=30)(RETRY_COUNT=20)(RETRY_DELAY=3)(ADDRESS_LIST=(LOAD_BALANCE=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=51521)))(CONNECT_DATA=(SERVICE_NAME=DEVPDB)))
spring.datasource.username=MRD_SCHEMA_OWNER
spring.datasource.password=MrdReport678
spring.datasource.driver-class=oracle.jdbc.driver.OracleDriver